### PR TITLE
Simplify Matrix decode, add defaults for fail-fast and max-parallel, add test

### LINKED ISSUE #625: Issue: a strategy clause without matrix 'disables' a job
## Act version

```none
$ ~/go/bin/act --version
Error: unknown flag: --version
$ strings ~/go/bin/act | grep '^mod.*v[0-9]\+\.[0-9]\+\.[0-9]\+'
mod	github.com/nektos/act	v0.2.21	h1:mx5wheBRwuwrCaZb+gL0QcxIQQCsUFKtafmamfqtfWU=
```

I'm on Gentoo Linux (if it matters).

## Expected behaviour

The job below is run when I type `~/go/bin/act` (it is run on GitHub Actions).

## Actual behaviour

The job below does not run when I type `~/go/bin/act`.

## Workflow

<details>
  <summary>workflow</summary>

```yaml
name: Hello, world!

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo Hello, world!
```
</details>

## Steps to reproduce

1. Create an empty git repository.
2. Place the workflow above into the `.github/workflows/hello_world.yml` file.
3. Run `~/go/bin/act`.

## `act` output

<details>
  <summary>Log</summary>

```none
$ ~/go/bin/act --verbose
DEBU[0000] Loading environment from /home/alex/p/p/test/.env 
DEBU[0000] Loading secrets from /home/alex/p/p/test/.secrets 
DEBU[0000] Loading workflows from '/home/alex/p/p/test/.github/workflows' 
DEBU[0000] Reading workflow '/home/alex/p/p/test/.github/workflows/hello_world.yml' 
DEBU[0000] Planning event: push 
```
</details>

## Looking a bit deeper

When I remove the `strategy` clause the job is run:

<details>
  <summary>workflow (without strategy clause)</summary>

```yaml
name: Hello, world!

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo Hello, world!
```
</details>

Or, when I add `matrix clause, the job is run too:

<details>
  <summary>workflow (with matrix clause)</summary>

```yaml
name: Hello, world!

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo Hello, world!
```
</details>

### LINKED ISSUE #760: Issue: panic: reflect: call of reflect.Value.Type on zero Value
## System information

- Operating System: Ubuntu 20.10
- Architecture: x86 64bit
- Apple M1: no
- Docker version: 20.10.2,
- `act` version: 0.2.23

## Expected behaviour

`act` does not crash when I run the following command:

`act --userns <my namespace> release`

## Actual behaviour

Running `act --userns <my namespace> release` results in the following error:

```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0xc00069f8b0, 0xc0001ae910)
	/opt/hostedtoolcache/go/1.16.5/x64/src/reflect/value.go:1908 +0x189
github.com/nektos/act/pkg/model.(*Job).Matrix(0xc0002f7800, 0x0)
	/home/runner/work/act/act/pkg/model/workflow.go:177 +0xd7
github.com/nektos/act/pkg/model.(*Job).GetMatrixes(0xc0002f7800, 0xc000236b00, 0x19, 0xc0002f7800)
	/home/runner/work/act/act/pkg/model/workflow.go:199 +0x76
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor(0xc000212a50, 0xc000212840, 0x5)
	/home/runner/work/act/act/pkg/runner/runner.go:119 +0x685
github.com/nektos/act/cmd.newRunCommand.func1(0xc000214000, 0xc00025a000, 0x1, 0x9, 0x0, 0x0)
	/home/runner/work/act/act/cmd/root.go:281 +0xc5f
github.com/spf13/cobra.(*Command).execute(0xc000214000, 0xc00024c000, 0x9, 0xc, 0xc000214000, 0xc00024c000)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000214000, 0x9, 0xc, 0xf)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/nektos/act/cmd.Execute(0xe70fe0, 0xc0004e2640, 0xe4d8bc, 0x6)
	/home/runner/work/act/act/cmd/root.go:71 +0x100c
main.main()
	/home/runner/work/act/act/main.go:33 +0x175
```

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```none
name: Create Packages
on: [release]

jobs:
  Package-Ubuntu-2104-64bit:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

```

</details>

## Steps to reproduce

1. Install `act`
2. Have your docker daemon use namespaces.
3. Run a workflow using `act -v --userns <namespace> release`.

## `act` output

<details>
  <summary>Log</summary>

```none
DEBU[0000] Loading environment from /home/phao5814/dev/souffle/souffle-forked/.env
DEBU[0000] Loading secrets from /home/phao5814/dev/souffle/souffle-forked/.secrets
DEBU[0000] Loading workflows from '/home/phao5814/dev/souffle/souffle-forked/.github/workflows'
DEBU[0000] Loading workflows recursively
DEBU[0000] Found workflow 'CI-Tests.yml' in '/home/phao5814/dev/souffle/souffle-forked/.github/workflows/CI-Tests.yml'
DEBU[0000] Found workflow 'cancel.yml' in '/home/phao5814/dev/souffle/souffle-forked/.github/workflows/cancel.yml'
DEBU[0000] Found workflow 'create-packages.yml' in '/home/phao5814/dev/souffle/souffle-forked/.github/workflows/create-packages.yml'
DEBU[0000] Reading workflow '/home/phao5814/dev/souffle/souffle-forked/.github/workflows/CI-Tests.yml'
DEBU[0000] Correcting if statements '/home/phao5814/dev/souffle/souffle-forked/.github/workflows/CI-Tests.yml'
DEBU[0000] Reading workflow '/home/phao5814/dev/souffle/souffle-forked/.github/workflows/cancel.yml'
DEBU[0000] Correcting if statements '/home/phao5814/dev/souffle/souffle-forked/.github/workflows/cancel.yml'
DEBU[0000] Reading workflow '/home/phao5814/dev/souffle/souffle-forked/.github/workflows/create-packages.yml'
DEBU[0000] Correcting if statements '/home/phao5814/dev/souffle/souffle-forked/.github/workflows/create-packages.yml'
DEBU[0000] Planning event: release
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0xc00061f8b0, 0xc0001ae9b0)
	/opt/hostedtoolcache/go/1.16.5/x64/src/reflect/value.go:1908 +0x189
github.com/nektos/act/pkg/model.(*Job).Matrix(0xc0002f7500, 0x0)
	/home/runner/work/act/act/pkg/model/workflow.go:177 +0xd7
github.com/nektos/act/pkg/model.(*Job).GetMatrixes(0xc0002f7500, 0xc0003fc760, 0x19, 0xc0002f7500)
	/home/runner/work/act/act/pkg/model/workflow.go:199 +0x76
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor(0xc00000caf8, 0xc00000c8e8, 0x5)
	/home/runner/work/act/act/pkg/runner/runner.go:119 +0x685
github.com/nektos/act/cmd.newRunCommand.func1(0xc000214000, 0xc00021b900, 0x1, 0xa, 0x0, 0x0)
	/home/runner/work/act/act/cmd/root.go:281 +0xc5f
github.com/spf13/cobra.(*Command).execute(0xc000214000, 0xc00024c000, 0xa, 0xc, 0xc000214000, 0xc00024c000)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000214000, 0xa, 0xc, 0xf)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/nektos/act/cmd.Execute(0xe70fe0, 0xc0004e4600, 0xe4d8bc, 0x6)
	/home/runner/work/act/act/cmd/root.go:71 +0x100c
main.main()
	/home/runner/work/act/act/main.go:33 +0x175
```

</details>

### PR DESCRIPTION
**Pull request by catthehacker**
fix[workflow]: default `max-parallel`
fix[workflow]: default `fail-fast`, it's `true`, not `false`
fix[workflow]: skipping over the job when `strategy:` is defined but `matrix:` isn't (fixes #625)
fix[workflow]: skip non-existing includes keys and hard fail on non-existing excludes keys
fix[workflow]: simplify Matrix decode (because I "think" I know how `yaml` works) (fixes #760)
fix[tests]: add test for planner and runner

### CODE REVIEW

**Comment by catthehacker** [comment]
shush, it works perfectly

**Comment by catthehacker** [comment]
well, at least it worked here https://github.com/nektos/act/pull/763/checks?sha=795cbfcca42729be183c05d275c34aaf04c3d223

**Comment by acjh** [comment]
> fix[workflow]: ... hard fail on non-existing excludes

> ```go
> // ... because that's what GitHub does for non-existing matrix keys, fail on exclude, ...
> ```

GitHub doesn't appear to do that.
e.g. [speedy-net/speedy-net/actions/runs/1025416111/workflow](https://github.com/speedy-net/speedy-net/actions/runs/1025416111/workflow) (Test only Python 3.6 and 3.7 on non-master/staging)

```yaml
strategy:
  matrix:
    python-version: [3.6, 3.7, 3.8, 3.9]
    is-master-or-staging:
      - ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' }}
    exclude:
      - python-version: 3.8
        is-master-or-staging: false
      - python-version: 3.9
        is-master-or-staging: false
```

**Comment by catthehacker** [comment]
It does
image

**Comment by acjh** [comment]
Could you share a link to that workflow and/or your `strategy` section?

**Comment by catthehacker** [comment]
It's the same as the one in this PR with one line diff in exclude
```diff
     strategy:
       fail-fast: false
       matrix:
         datacenter:
           - site-c
           - site-d
         exclude:
           - datacenter: site-d
             node-version: 14.x
             site: staging
+          - php-version: '5.4'
         include:
           - php-version: '5.4'
           - datacenter: site-a
             node-version: 10.x
             site: prod
           - datacenter: site-b
             node-version: 12.x
             site: dev
         node-version: [14.x, 16.x]
         site:
           - staging
       max-parallel: 2
```

**Comment by catthehacker** [comment]
This also fails
image

**Comment by catthehacker** [comment]
> > fix[workflow]: ... hard fail on non-existing excludes
> 
> > ```go
> > // ... because that's what GitHub does for non-existing matrix keys, fail on exclude, ...
> > ```
> 
> GitHub doesn't appear to do that.
> e.g. [speedy-net/speedy-net/actions/runs/1025416111/workflow](https://github.com/speedy-net/speedy-net/actions/runs/1025416111/workflow) (Test only Python 3.6 and 3.7 on non-master/staging)
> 
> ```yaml
> strategy:
>   matrix:
>     python-version: [3.6, 3.7, 3.8, 3.9]
>     is-master-or-staging:
>       - ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' }}
>     exclude:
>       - python-version: 3.8
>         is-master-or-staging: false
>       - python-version: 3.9
>         is-master-or-staging: false
> ```

Your example has defined all required keys in matrix so that's why it's not failing

**Comment by acjh** [comment]
Ah, I misunderstood "non-existing excludes" as "excludes not existing in the cross product".
Instead, you mean "excludes with any key not existing in the matrix".

Thanks for the clarification and your good work!

**Comment by catthehacker** [comment]
updated commit description to mention that it's for keys

File: pkg/model/workflow.go [hunk 1]
```diff
@@ -173,65 +207,84 @@ func (j *Job) Environment() map[string]string {
...
+						log.Debugf("Skipping matrix '%v' due to exclude '%v'", matrix, exclude)
+						continue MATRIX
+					}
+				}
+				matrixes = append(matrixes, matrix)
+			}
+			for _, include := range includes {
+				log.Debugf("Adding include '%v'", include)
+				matrixes = append(matrixes, include)
+			}
```
Comment (ChristopherHX) [inline pkg/model/workflow.go:285]: Nothing which blocks this PR,
I think you aren't really aware of the behavior of the matrix include statement, (this is not introduced in this PR, but not fixed either)

Example Workflow run:
https://github.com/actions/runner/actions/runs/1082604590/workflow

This workflow demonstrates that includes needs to be handeled differently, if your matrix cross product is non empty and you have includes.

In [my c# implementation](https://github.com/ChristopherHX/runner.server/blob/5d55db086c97e9bc45e97f18fadaf4043588fdf0/src/Runner.Server/Controllers/MessageController.cs#L890-L914) of this,
- Create the cross product (this seems to work in act with this PR)
- apply excludes (this seems to work in act with this PR)
- Merge the cross product if all member which are both in the cross product and include mapping are equal (added members or matrix entries to the cross product via include are not considered), otherwise do it like this code does.

Well this might be not perfect either, but this seems for me to be more like github actions.

**Review by cplee — APPROVED** [review]
