### PR TITLE
fix: processing of strategy.matrix.include

### LINKED ISSUE #769: Issue: Matrix construction does not match GitHub
Nothing which blocks this PR,
I think you aren't really aware of the behavior of the matrix include statement, (this is not introduced in this PR, but not fixed either)

Example Workflow run:
https://github.com/actions/runner/actions/runs/1082604590/workflow

This workflow demonstrates that includes needs to be handeled differently, if your matrix cross product is non empty and you have includes.

In [my c# implementation](https://github.com/ChristopherHX/runner.server/blob/5d55db086c97e9bc45e97f18fadaf4043588fdf0/src/Runner.Server/Controllers/MessageController.cs#L890-L914) of this,
- Create the cross product (this seems to work in act with this PR)
- apply excludes (this seems to work in act with this PR)
- Merge the cross product if all member which are both in the cross product and include mapping are equal (added members or matrix entries to the cross product via include are not considered), otherwise do it like this code does.

Well this might be not perfect either, but this seems for me to be more like github actions.

_Originally posted by @ChristopherHX in https://github.com/nektos/act/pull/763#discussion_r680346444_

### LINKED ISSUE #1182: Dynamic matrix with include: does nothing
### Bug report info

Tested with 0.2.26  and 2.2.27-dev
```
act version:            v0.2.27-dev
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 4
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:
	/Users/jayvdb/.actrc:
		#-P self-hosted=catthehacker/ubuntu:act-latest
		-P self-hosted=ubuntu:jammy
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
		ubuntu-16.04=catthehacker/ubuntu:act-16.04
Build info:
	Go version:            go1.18.2
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:
	Build settings:
		-compiler:            gc
		CGO_ENABLED:          1
		CGO_CFLAGS:
		CGO_CPPFLAGS:
		CGO_CXXFLAGS:
		CGO_LDFLAGS:
		GOARCH:               amd64
		GOOS:                 darwin
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         bc0f09b9ea1df599011787f51d296bd793e7cfb5
		vcs.time:             2022-05-24T20:49:12Z
		vcs.modified:         false
Docker Engine:
	Engine version:        20.10.13
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:
	OS arch:               x86_64
	OS kernel:             5.10.104-linuxkit
	OS CPU:                2
	OS memory:             7960 MB
	Security options:
		name=seccomp,profile=default
		name=cgroupns
```

```
act version:            0.2.26
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 4
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:
	/Users/jayvdb/.actrc:
		#-P self-hosted=catthehacker/ubuntu:act-latest
		-P self-hosted=ubuntu:jammy
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
		ubuntu-16.04=catthehacker/ubuntu:act-16.04
Docker Engine:
	Engine version:        20.10.13
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:
	OS arch:               x86_64
	OS kernel:             5.10.104-linuxkit
	OS CPU:                2
	OS memory:             7960 MB
	Security options:
		name=seccomp,profile=default
		name=cgroupns
```

### Command used with act

```sh
act -j job2
```

### Describe issue

The example is here https://github.community/t/how-to-conditionally-include-exclude-items-in-matrix-eg-based-on-branch/16853/7
`act -j job2` will run `job1` but doesnt run job2.

### Link to GitHub repository

_No response_

### Workflow content

```yml
name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: build
```

### Relevant log output

```sh
% ~/go/bin/act -j job2
[bug/job1] 🚀  Start image=catthehacker/ubuntu:act-latest
[bug/job1]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=false
[bug/job1]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[bug/job1]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[bug/job1]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root workdir=
[bug/job1] ⭐  Run echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
[bug/job1]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/set-matrix] user= workdir=
[bug/job1]   ⚙  ::set-output:: matrix={"include":[{"project":"foo","config":"Debug"},{"project":"bar","config":"Release"}]}
[bug/job1]   ✅  Success - echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
```
```


### Additional information

_No response_

### LINKED ISSUE #1223: act silently stopping
### Bug report info

```plain text
juliangro@x299-desktop:~/Software/act$ ./act --bug-report
act version:            0.2.26
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/juliangro/.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
Docker Engine:
	Engine version:        20.10.14+dfsg1
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         systemd
	Storage driver:        btrfs
	Registry URI:          https://index.docker.io/v1/
	OS:                    Debian GNU/Linux bookworm/sid
	OS type:               linux
	OS version:            
	OS arch:               x86_64
	OS kernel:             5.18.0-1-amd64
	OS CPU:                12
	OS memory:             31811 MB
	Security options:
		name=apparmor
		name=seccomp,profile=default
		name=cgroupns

juliangro@x299-desktop:~/Software/act$
```

### Command used with act

```sh
./act -W /home/juliangro/git/temp/project-athena-docker/.github/workflows/master_docker_build.yml -C /home/juliangro/git/temp/project-athena-docker/ -v --detect-event
```

### Describe issue

Act just silently stops when trying to run my workflow.
As you can see in the debug output it just says "false" without any meaningfull information.

### Link to GitHub repository

_No response_

### Workflow content

```yml
name: Master CI Docker Server Build

on:
  push
#  push:
#    branches:
#      - master

env:
  BUILD_TYPE: Release
  BUILD_NUMBER: ${{ github.run_number }}
  CI_BUILD: Github
  GIT_COMMIT: ${{ github.sha }}
  RELEASE_TYPE: PRODUCTION
  RELEASE_NUMBER: ${{ github.run_number }}
  STABLE_BUILD: 0
  UPLOAD_BUCKET: overte-public
  UPLOAD_REGION: fra1
  UPLOAD_ENDPOINT: "https://fra1.digitaloceanspaces.com"
  # Use Docker BuildKit backend
  DOCKER_BUILDKIT: 1


jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            apt-dependencies: docker.io
          # Do not change the names of self-hosted runners without knowing what you are doing, as they correspond to labels that have to be set on the runner.
          #~ - os: self-hosted_debian-11_aarch64
            #~ build_type: full
            #~ apt-dependencies: docker.io
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
    - name: Report Build Number
      shell: bash
      run: |

        echo "Build number: $BUILD_NUMBER"

    - uses: actions/checkout@v1
      with:
        submodules: false
        fetch-depth: 1

    - name: Install dependencies
      shell: bash
      run: |
      
          echo "Updating apt repository index"
          sudo apt update || exit 1

          echo "Installing apt packages"
          sudo apt install -y ${{ matrix.apt-dependencies }} || exit 1

    - name: Create Docker environment
      shell: bash
      run: mkdir build

    - name: Start Docker build container
      working-directory: ${{runner.workspace}}
      run: docker build -f tools/ci-scripts/docker_package/Dockerfile_build .
```

### Relevant log output

```sh
juliangro@x299-desktop:~/Software/act$ ./act -W /home/juliangro/git/temp/project-athena-docker/.github/workflows/master_docker_build.yml -C /home/juliangro/git/temp/project-athena-docker/ -v --detect-event
DEBU[0000] Loading environment from /home/juliangro/git/temp/project-athena-docker/.env 
DEBU[0000] Loading secrets from /home/juliangro/git/temp/project-athena-docker/.secrets 
DEBU[0000] Loading workflow '/home/juliangro/git/temp/project-athena-docker/.github/workflows/master_docker_build.yml' 
DEBU[0000] Reading workflow '/home/juliangro/git/temp/project-athena-docker/.github/workflows/master_docker_build.yml' 
DEBU[0000] Using detected workflow event: push          
DEBU[0000] Planning event: push                         
DEBU[0000] Loading slug from git directory '/home/juliangro/git/temp/project-athena-docker/.git' 
DEBU[0000] Loading revision from git directory '/home/juliangro/git/temp/project-athena-docker/.git' 
DEBU[0000] Found revision: 581aa24a7890d44654e4b84a9cfe3686f63653fd 
DEBU[0000] HEAD points to '581aa24a7890d44654e4b84a9cfe3686f63653fd' 
DEBU[0000] using github ref: refs/heads/docker_experiment 
DEBU[0000] Found revision: 581aa24a7890d44654e4b84a9cfe3686f63653fd 
DEBU[0000] Loading slug from git directory '/home/juliangro/git/temp/project-athena-docker/.git' 
DEBU[0000] Loading revision from git directory '/home/juliangro/git/temp/project-athena-docker/.git' 
DEBU[0000] Found revision: 581aa24a7890d44654e4b84a9cfe3686f63653fd 
DEBU[0000] HEAD points to '581aa24a7890d44654e4b84a9cfe3686f63653fd' 
DEBU[0000] using github ref: refs/heads/docker_experiment 
DEBU[0000] Found revision: 581aa24a7890d44654e4b84a9cfe3686f63653fd 
DEBU[0000] false                                        
juliangro@x299-desktop:~/Software/act$
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ChristopherHX**
Refactored GetMatrices to more closely match my runner.server project and github actions.
- include properties are now merged with the matrix cross product, if common keys match with an existing entry
- include properties not matched against any existing entry are added as an additional matrix instance

Partially fixes #769
fixes #1182
resolves #1223

**Known Issues**, based on recent research in my related project
- Matrix Keys are case insensitive, but not in act
- Object Keys are case insensitive in deepequal, but not in act
- Scalar values are compared with abstract equal, see expression evaluator
  null == '' == 0
- prevent empty matrices by always return a default matrix entry if everything is empty

### CODE REVIEW

File: pkg/model/workflow.go [hunk 1]
```diff
@@ -224,26 +224,37 @@ func (j *Job) GetMatrixes() []map[string]interface{} {
...
 							if _, ok := m[k]; ok {
 								includes = append(includes, i)
+								extraInclude = false
 								break
 							}
 						}
+						if extraInclude {
+							extraIncludes = append(extraIncludes, i)
+						}
 					}
```
Comment (ChristopherHX) [inline pkg/model/workflow.go:244]: Why do we have this case? Doesn't this allow invalid syntax.

File: pkg/model/workflow_test.go [hunk 2]
```diff
@@ -247,6 +247,7 @@ func TestReadWorkflow_Strategy(t *testing.T) {
 			{"datacenter": "site-c", "node-version": "14.x", "site": "staging"},
 			{"datacenter": "site-c", "node-version": "16.x", "site": "staging"},
 			{"datacenter": "site-d", "node-version": "16.x", "site": "staging"},
+                        {"php-version": 5.4},
```
Comment (ChristopherHX) [inline pkg/model/workflow_test.go:250]: I modified this Test, correct me if my expectation is wrong.

**Review by KnisterPeter — APPROVED** [review]

**Review by cplee — APPROVED** [review]
