### PR TITLE
fix: rework setupShellCommand

### LINKED ISSUE #865: Issue: Unable to parse file paths that include spaces
## System information

- Operating System: macOS
- Architecture: x64 (64-bit)
- Apple M1: no
- Docker version: 20.10.8
- `act` version: 0.2.24

## Expected behaviour

When `uses/setup-node@v2` is used, the version of node should print

## Actual behaviour

I have spaces in my file path `/Users/[my_username]/Code Projects`.  When I run `npm -v` I receive the error `bash: /Users/[my_username]/Code: No such file or directory`. 

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```yaml
# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
         run: npm -v

```

</details>

## `act` output
if filepath = /Users/username/Code Projects/repo

`bash: /Users/username/Code : No such file or directory`

<details>
  <summary>Log</summary>

```none
PASTE YOUR LOG HERE
```

</details>

### LINKED ISSUE #884: Issue:  Unable to run `pwsh` steps
## System information

- Operating System: Windows 10
- Architecture: x64 (64-bit)
- Docker version:  `20.10.18`
- Docker image used in `act`: `ghcr.io/catthehacker/ubuntu:pwsh-20.04`
- `act` version: act version `0.2.24`

## Expected behaviour

Running [this](https://github.com/extendr/extendr/blob/master/.github/workflows/test.yml) workflow 
```pwsh
act -v -j tests_no_bindgen -P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:pwsh-20.04
```
The workflow finishes suceesfully.

## Actual behaviour

```
[Tests/ubuntu-20.04 (R-release rust-stable)-3       ]   🐳  docker exec cmd=[pwsh -command . '/mnt/d/OneDrive/Development/OSS/extendr/workflow/5'] user=
[Tests/ubuntu-20.04 (R-release rust-stable)-3       ] Exec command '[pwsh -command . '/mnt/d/OneDrive/Development/OSS/extendr/workflow/5']'
| ResourceUnavailable: Program '5' failed to run: Exec format errorAt line:1 char:1
| + . '/mnt/d/OneDrive/Development/OSS/extendr/workflow/5'
| + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
time="2021-11-15T19:02:58+03:00" level=debug msg="exit with `FAILURE`: 1"
[Tests/ubuntu-20.04 (R-release rust-stable)-3       ]   ❌  Failure - Configure Linux
```

## Workflow and/or repository
- [extendr/extendr](https://github.com/extendr/extendr)
- [test.yml](https://github.com/extendr/extendr/blob/master/.github/workflows/test.yml)

## Possible explanation
According to the [docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsshell), when executing PowerShell scripts, GHA appends `.ps1` to the file name.
If I connect to the container and modify the name of the faulty workflow (in this case, `5`), I can execute `pwsh -command . '/mnt/d/OneDrive/Development/OSS/extendr/workflow/5'` with no problem (I mean, this particular problem goes away).

## Steps to reproduce
```pwsh
git clone https://github.com/extendr/extendr
cd extendr
act -v -j tests_no_bindgen -P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:pwsh-20.04
```

<details>
  <summary>Log</summary>

```none

```

</details>

### PR DESCRIPTION
**Pull request by catthehacker**
* move all logic to separate function so we can test that later
* split `step.Shell` and `step.WorkingDirectory` setup into own funcs
* general cleanup of function
* use `ActPath` to not collide with checked out repository (also avoids issues if path contains spaces)
* use `shellquote.Split()` instead of `strings.Fields()` for better command split
* replace single string concat with `fmt`

Fixes #884 
Fixes #865 

Signed-off-by: hackercat <me@hackerc.at>

### CODE REVIEW

File: pkg/runner/step_context.go [hunk 1]
```diff
@@ -185,87 +185,106 @@ func (sc *StepContext) setupEnv(ctx context.Context) (ExpressionEvaluator, error
...
+	// for now I'm going to leave below logic, will address it in different PR
+	// https://github.com/actions/runner/blob/9a829995e02d2db64efb939dc2f283002595d4d9/src/Runner.Worker/Handlers/ScriptHandler.cs#L87-L91
+	if rc.Run.Job().Container() != nil {
+		if rc.Run.Job().Container().Image != "" && step.Shell == "" {
+			step.Shell = "sh"
 		}
+	}
+}
+
+// TODO: Currently we just ignore top level keys, BUT we should return proper error on them
```
Comment (KnisterPeter) [inline pkg/runner/step_context.go:231]: I'm not sure if I do understand your todo-comment here. Is it related to not having a test workflow with a top-level default shell/workdir?

**Review by KnisterPeter — APPROVED** [review]
Looks fine with just a question from my side

File: pkg/runner/step_context.go (hunk 1 above)
Comment (catthehacker) [reply pkg/runner/step_context.go:231]:
```
// TODO: Currently we just ignore top level keys, BUT we should return proper error on them
// BUTx2 I leave this for when we rewrite act to use actionlint for workflow validation
// so we return proper errors before any execution or spawning containers
// it will error anyway with:
// OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "${{": executable file not found in $PATH: unknown
```

Comment (catthehacker) [reply pkg/runner/step_context.go:231]: the todo is not for `setupShellCommand` but for workflow parser to validate top level keys cannot use contexts

Comment (ZauberNerd) [reply pkg/runner/step_context.go:231]: Then it looks like the integration tests you've added do not test for: https://github.com/nektos/act/pull/930/files/18c648a0e35be856afe78bb2948ab4e854fa2116#diff-d428984a0cfea053a858f85bae301c213d3f37466ac24fb031ad514676e6955eR216 right?

Comment (catthehacker) [reply pkg/runner/step_context.go:231]: Yes

**Review by cplee — APPROVED** [review]
