### PR TITLE
fix: don't overwrite with empty cmd/entrypoint

### LINKED ISSUE #917: Issue: failed to run docker containers as steps
## System information

- Operating System: Debian Linux
- Architecture: amd64
- Docker version: Docker version 20.10.8+dfsg1, build 3967b7d
- Docker image used in `act`: node:12-buster-slim
- `act` version: Latest `master`

## Expected behaviour

This workflow should output the node.js version installed in the alpine container:

```yml
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://node:alpine
        with:
          args: -v
```

## Actual behaviour

This is the panic log:

```
DEBU[0000] Loading environment from /tmp/act-test/.env  
DEBU[0000] Loading secrets from /tmp/act-test/.secrets  
DEBU[0000] Loading workflows from '/tmp/act-test/.github/workflows' 
DEBU[0000] Loading workflows recursively                
DEBU[0000] Found workflow 'test.yml' in '/tmp/act-test/.github/workflows/test.yml' 
DEBU[0000] Reading workflow '/tmp/act-test/.github/workflows/test.yml' 
DEBU[0000] Correcting if statements '/tmp/act-test/.github/workflows/test.yml' 
DEBU[0000] Planning event: push                         
DEBU[0000] Loading slug from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] Loading revision from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] HEAD points to 'e5ff86528d69197caaf191cd157a609333c52787' 
DEBU[0000] using github ref: refs/heads/docker-uses     
DEBU[0000] context steps => map[]                       
DEBU[0000] context env => map[ACT:true]                 
DEBU[0000] context needs => map[]                       
[CI/build] 🚀  Start image=node:12-buster-slim
DEBU[0000] Loading slug from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] Loading revision from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] HEAD points to 'e5ff86528d69197caaf191cd157a609333c52787' 
DEBU[0000] using github ref: refs/heads/docker-uses     
[CI/build]   🐳  docker pull image=node:12-buster-slim platform= username= forcePull=false
[CI/build]   🐳  docker pull node:12-buster-slim
DEBU[0000] Image exists? true                           
[CI/build] Removed container: 1eb85585a1a28a285a05dfe1a4552fd7a1749557ddcef4b86db084d761dc8fcf
[CI/build]   🐳  docker volume rm act-CI-build
[CI/build]   🐳  docker create image=node:12-buster-slim platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CI/build] Created container name=act-CI-build id=3b969259a97e0bd45c7cd23c8b1a6a41e1b7d4daf42ce351686c7b2be709174e from image node:12-buster-slim (platform: )
[CI/build] ENV ==> [RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_TEMP=/tmp]
[CI/build]   🐳  docker run image=node:12-buster-slim platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CI/build] Starting container: 3b969259a97e0bd45c7cd23c8b1a6a41e1b7d4daf42ce351686c7b2be709174e
[CI/build] Started container: 3b969259a97e0bd45c7cd23c8b1a6a41e1b7d4daf42ce351686c7b2be709174e
[CI/build]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root workdir=
[CI/build] Exec command '[mkdir -m 0777 -p /var/run/act]'
[CI/build] Working directory '/tmp/act-test'
DEBU[0000] Writing entry to tarball workflow/event.json len:2 
DEBU[0000] Writing entry to tarball workflow/envs.txt len:0 
DEBU[0000] Writing entry to tarball workflow/paths.txt len:0 
[CI/build] Extracting content to '/var/run/act/'
DEBU[0000] Loading slug from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] Loading revision from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] HEAD points to 'e5ff86528d69197caaf191cd157a609333c52787' 
DEBU[0000] using github ref: refs/heads/docker-uses     
DEBU[0000] Loading slug from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] Loading revision from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] HEAD points to 'e5ff86528d69197caaf191cd157a609333c52787' 
DEBU[0000] using github ref: refs/heads/docker-uses     
DEBU[0000] context steps => map[0:map[conclusion:success outcome:success outputs:map[]]] 
DEBU[0000] context env => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/docker-uses GITHUB_REPOSITORY:ZauberNerd/act-test GITHUB_REPOSITORY_OWNER:ZauberNerd GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:e5ff86528d69197caaf191cd157a609333c52787 GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/tmp/act-test ImageOS:ubuntu20 NODE_VERSION:12.22.7 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: YARN_VERSION:1.22.15] 
DEBU[0000] context needs => map[]                       
DEBU[0000] Loading slug from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] Loading revision from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] HEAD points to 'e5ff86528d69197caaf191cd157a609333c52787' 
DEBU[0000] using github ref: refs/heads/docker-uses     
DEBU[0000] context steps => map[0:map[conclusion:success outcome:success outputs:map[]]] 
DEBU[0000] context env => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/docker-uses GITHUB_REPOSITORY:ZauberNerd/act-test GITHUB_REPOSITORY_OWNER:ZauberNerd GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:e5ff86528d69197caaf191cd157a609333c52787 GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/tmp/act-test ImageOS:ubuntu20 NODE_VERSION:12.22.7 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: YARN_VERSION:1.22.15] 
DEBU[0000] context needs => map[]                       
DEBU[0000] context env => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/docker-uses GITHUB_REPOSITORY:ZauberNerd/act-test GITHUB_REPOSITORY_OWNER:ZauberNerd GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:e5ff86528d69197caaf191cd157a609333c52787 GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/tmp/act-test INPUT_ARGS:-v ImageOS:ubuntu20 NODE_VERSION:12.22.7 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: YARN_VERSION:1.22.15] 
[CI/build] setupEnv => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/docker-uses GITHUB_REPOSITORY:ZauberNerd/act-test GITHUB_REPOSITORY_OWNER:ZauberNerd GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:e5ff86528d69197caaf191cd157a609333c52787 GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/tmp/act-test INPUT_ARGS:-v ImageOS:ubuntu20 NODE_VERSION:12.22.7 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: YARN_VERSION:1.22.15]
[CI/build] ⭐  Run docker://node:alpine
DEBU[0000] Loading slug from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] Loading revision from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] HEAD points to 'e5ff86528d69197caaf191cd157a609333c52787' 
DEBU[0000] using github ref: refs/heads/docker-uses     
DEBU[0000] context steps => map[0:map[conclusion:success outcome:success outputs:map[]]] 
DEBU[0000] context env => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/docker-uses GITHUB_REPOSITORY:ZauberNerd/act-test GITHUB_REPOSITORY_OWNER:ZauberNerd GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:e5ff86528d69197caaf191cd157a609333c52787 GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/tmp/act-test ImageOS:ubuntu20 NODE_VERSION:12.22.7 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: YARN_VERSION:1.22.15] 
DEBU[0000] context needs => map[]                       
DEBU[0000] Loading slug from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] Loading revision from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] HEAD points to 'e5ff86528d69197caaf191cd157a609333c52787' 
DEBU[0000] using github ref: refs/heads/docker-uses     
DEBU[0000] context steps => map[0:map[conclusion:success outcome:success outputs:map[]]] 
DEBU[0000] context env => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/docker-uses GITHUB_REPOSITORY:ZauberNerd/act-test GITHUB_REPOSITORY_OWNER:ZauberNerd GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:e5ff86528d69197caaf191cd157a609333c52787 GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/tmp/act-test ImageOS:ubuntu20 NODE_VERSION:12.22.7 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: YARN_VERSION:1.22.15] 
DEBU[0000] context needs => map[]                       
DEBU[0000] Loading slug from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] Loading revision from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] HEAD points to 'e5ff86528d69197caaf191cd157a609333c52787' 
DEBU[0000] using github ref: refs/heads/docker-uses     
DEBU[0000] context steps => map[0:map[conclusion:success outcome:success outputs:map[]]] 
DEBU[0000] context env => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/docker-uses GITHUB_REPOSITORY:ZauberNerd/act-test GITHUB_REPOSITORY_OWNER:ZauberNerd GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:e5ff86528d69197caaf191cd157a609333c52787 GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/tmp/act-test ImageOS:ubuntu20 NODE_VERSION:12.22.7 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: YARN_VERSION:1.22.15] 
DEBU[0000] context needs => map[]                       
DEBU[0000] context env => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/docker-uses GITHUB_REPOSITORY:ZauberNerd/act-test GITHUB_REPOSITORY_OWNER:ZauberNerd GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:e5ff86528d69197caaf191cd157a609333c52787 GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/tmp/act-test INPUT_ARGS:-v ImageOS:ubuntu20 NODE_VERSION:12.22.7 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: YARN_VERSION:1.22.15] 
[CI/build]   🐳  docker pull image=node:alpine platform= username= forcePull=false
[CI/build]   🐳  docker pull node:alpine
DEBU[0000] Image exists? true                           
[CI/build]   🐳  docker create image=node:alpine platform= entrypoint=[] cmd=["-v"]
[CI/build] Created container name=act-CI-build-0 id=c07bf68d98de373eb1d09b4f76a89f37558a4829a5756e0453b1884b58990b96 from image node:alpine (platform: )
[CI/build] ENV ==> [RUNNER_PERFLOG=/dev/null YARN_VERSION=1.22.15 GITHUB_TOKEN= ImageOS=ubuntu20 GITHUB_ACTION_REPOSITORY= GITHUB_GRAPHQL_URL=https://api.github.com/graphql GITHUB_REPOSITORY_OWNER=ZauberNerd GITHUB_ACTION_REF= NODE_VERSION=12.22.7 CI=true GITHUB_JOB=build GITHUB_RETENTION_DAYS=0 GITHUB_RUN_ID=1 GITHUB_BASE_REF= GITHUB_EVENT_NAME=push GITHUB_ACTIONS=true GITHUB_REF=refs/heads/docker-uses INPUT_ARGS=-v RUNNER_TRACKING_ID= GITHUB_ENV=/var/run/act/workflow/envs.txt GITHUB_SHA=e5ff86528d69197caaf191cd157a609333c52787 GITHUB_REPOSITORY=ZauberNerd/act-test GITHUB_SERVER_URL=https://github.com GITHUB_WORKFLOW=CI GITHUB_PATH=/var/run/act/workflow/paths.txt GITHUB_HEAD_REF= GITHUB_RUN_NUMBER=1 ACT=true GITHUB_EVENT_PATH=/var/run/act/workflow/event.json PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin GITHUB_ACTOR=nektos/act GITHUB_ACTION=0 GITHUB_WORKSPACE=/tmp/act-test GITHUB_API_URL=https://api.github.com RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_TEMP=/tmp]
[CI/build]   🐳  docker run image=node:alpine platform= entrypoint=[] cmd=["-v"]
[CI/build] Starting container: c07bf68d98de373eb1d09b4f76a89f37558a4829a5756e0453b1884b58990b96
DEBU[0000] Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "-v": executable file not found in $PATH: unknown
github.com/nektos/act/pkg/container.(*containerReference).start.func1
	/home/markusw/source/act/pkg/container/docker_run.go:745
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:146
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:133
github.com/nektos/act/pkg/common.Executor.IfNot.func1
	/home/markusw/source/act/pkg/common/executor.go:164
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:146
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:146
github.com/nektos/act/pkg/common.Executor.Finally.func1
	/home/markusw/source/act/pkg/common/executor.go:180
github.com/nektos/act/pkg/common.Executor.Finally.func1
	/home/markusw/source/act/pkg/common/executor.go:180
github.com/nektos/act/pkg/runner.(*StepContext).runUsesContainer.func1
	/home/markusw/source/act/pkg/runner/step_context.go:328
github.com/nektos/act/pkg/runner.(*RunContext).newStepExecutor.func1
	/home/markusw/source/act/pkg/runner/run_context.go:339
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:146
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:133
github.com/nektos/act/pkg/common.Executor.Finally.func1
	/home/markusw/source/act/pkg/common/executor.go:180
github.com/nektos/act/pkg/common.Executor.Finally.func1
	/home/markusw/source/act/pkg/common/executor.go:180
github.com/nektos/act/pkg/common.Executor.If.func1
	/home/markusw/source/act/pkg/common/executor.go:154
github.com/nektos/act/pkg/common.Executor.Finally.func1
	/home/markusw/source/act/pkg/common/executor.go:180
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor.func1
	/home/markusw/source/act/pkg/runner/runner.go:157
github.com/nektos/act/pkg/common.Executor.ChannelError.func1
	/home/markusw/source/act/pkg/common/executor.go:125
github.com/nektos/act/pkg/common.NewParallelExecutor.func1.1
	/home/markusw/source/act/pkg/common/executor.go:101
runtime.goexit
	/home/markusw/.gvm/gos/go1.16.3/src/runtime/asm_amd64.s:1371 
[CI/build] Removed container: c07bf68d98de373eb1d09b4f76a89f37558a4829a5756e0453b1884b58990b96
[CI/build]   ❌  Failure - docker://node:alpine
DEBU[0000] Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "-v": executable file not found in $PATH: unknown
github.com/nektos/act/pkg/container.(*containerReference).start.func1
	/home/markusw/source/act/pkg/container/docker_run.go:745
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:146
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:133
github.com/nektos/act/pkg/common.Executor.IfNot.func1
	/home/markusw/source/act/pkg/common/executor.go:164
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:146
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:146
github.com/nektos/act/pkg/common.Executor.Finally.func1
	/home/markusw/source/act/pkg/common/executor.go:180
github.com/nektos/act/pkg/common.Executor.Finally.func1
	/home/markusw/source/act/pkg/common/executor.go:180
github.com/nektos/act/pkg/runner.(*StepContext).runUsesContainer.func1
	/home/markusw/source/act/pkg/runner/step_context.go:328
github.com/nektos/act/pkg/runner.(*RunContext).newStepExecutor.func1
	/home/markusw/source/act/pkg/runner/run_context.go:339
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:146
github.com/nektos/act/pkg/common.Executor.Then.func1
	/home/markusw/source/act/pkg/common/executor.go:133
github.com/nektos/act/pkg/common.Executor.Finally.func1
	/home/markusw/source/act/pkg/common/executor.go:180
github.com/nektos/act/pkg/common.Executor.Finally.func1
	/home/markusw/source/act/pkg/common/executor.go:180
github.com/nektos/act/pkg/common.Executor.If.func1
	/home/markusw/source/act/pkg/common/executor.go:154
github.com/nektos/act/pkg/common.Executor.Finally.func1
	/home/markusw/source/act/pkg/common/executor.go:180
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor.func1
	/home/markusw/source/act/pkg/runner/runner.go:157
github.com/nektos/act/pkg/common.Executor.ChannelError.func1
	/home/markusw/source/act/pkg/common/executor.go:125
github.com/nektos/act/pkg/common.NewParallelExecutor.func1.1
	/home/markusw/source/act/pkg/common/executor.go:101
runtime.goexit
	/home/markusw/.gvm/gos/go1.16.3/src/runtime/asm_amd64.s:1371 
DEBU[0000] Loading slug from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] Loading revision from git directory '/tmp/act-test/.git' 
DEBU[0000] Found revision: e5ff86528d69197caaf191cd157a609333c52787 
DEBU[0000] HEAD points to 'e5ff86528d69197caaf191cd157a609333c52787' 
DEBU[0000] using github ref: refs/heads/docker-uses     
DEBU[0000] context steps => map[0:map[conclusion:failure outcome:failure outputs:map[]]] 
DEBU[0000] context env => map[ACT:true CI:true GITHUB_ACTION:0 GITHUB_ACTIONS:true GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:build GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/heads/docker-uses GITHUB_REPOSITORY:ZauberNerd/act-test GITHUB_REPOSITORY_OWNER:ZauberNerd GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:e5ff86528d69197caaf191cd157a609333c52787 GITHUB_TOKEN: GITHUB_WORKFLOW:CI GITHUB_WORKSPACE:/tmp/act-test ImageOS:ubuntu20 NODE_VERSION:12.22.7 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID: YARN_VERSION:1.22.15] 
DEBU[0000] context needs => map[]                       
Error: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "-v": executable file not found in $PATH: unknown
```

### PR DESCRIPTION
**Pull request by catthehacker**
fixes #917
Signed-off-by: Ryan <me@hackerc.at>

### CODE REVIEW

**Review by KnisterPeter — APPROVED** [review]

File: pkg/runner/step_docker.go [hunk 1]
```diff
@@ -58,7 +58,10 @@ func (sd *stepDocker) runUsesContainer() common.Executor {
 		if err != nil {
 			return err
 		}
-		entrypoint := strings.Fields(eval.Interpolate(step.With["entrypoint"]))
+		entrypoint, err := shellquote.Split(eval.Interpolate(step.With["entrypoint"]))
+		if err != nil {
+			return err
+		}
```
Comment (ChristopherHX) [inline pkg/runner/step_docker.go:64]: Can we get rid of any split of entrypoint? ( My suggestion might make the linter unhappy )

```suggestion
		entrypoint := []string{eval.Interpolate(step.With["entrypoint"])}
```
My actions/runner local tool supports this:
```
[uses-docker-url / test] Running: Run ubuntu.fritz.box/entrypointwithspaces
|##[group]Run docker://ubuntu.fritz.box/entrypointwithspaces
|with:
|  entrypoint: /path with spaces/node
|  args: -v
|##[endgroup]
|##[command]C:\Program Files\Docker\Docker\resources\bin\docker.EXE inspect --format="{{.Os}}/{{.Architecture}}" ubuntu.fritz.box/entrypointwithspaces
|linux/amd64
|##[command]C:\Program Files\Docker\Docker\resources\bin\docker.EXE run --name ubuntufritzboxentrypointwithspaces_d4ca9e --label 8f0fd6 --workdir /github/workspace --rm -e INPUT_ENTRYPOINT -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKFLOW -e GITHUB_REPOSITORY -e GITHUB_SHA -e GITHUB_REPOSITORY_OWNER -e GITHUB_REF -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_REF_NAME -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_ACTOR -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/path with spaces/node" -v "/var/run/docker.soc...
|v16.13.1
[uses-docker-url / test] Succeeded: Run ubuntu.fritz.box/entrypointwithspaces
```

**Review by ChristopherHX — APPROVED** [review]

File: pkg/runner/step_docker.go (hunk 1 above)
Comment (catthehacker) [reply pkg/runner/step_docker.go:64]: Will that work with nested quotations, escaping, mixed quote style, etc.?

Comment (ZauberNerd) [reply pkg/runner/step_docker.go:64]: In the docs it says that `entrypoint:` only accepts a single string: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswithentrypoint - so I suppose the suggestion from @ChristopherHX looks correct

**Review by ZauberNerd — DISMISSED** [review]

**Review by KnisterPeter — DISMISSED** [review]

**Review by cplee — APPROVED** [review]

File: pkg/runner/step_docker.go (hunk 1 above)
Comment (catthehacker) [reply pkg/runner/step_docker.go]: it's annoying and confusing because actions are allowed to use more than one argv for `entrypoint` but it's not allowed in workflows
